const root=document.documentElement,theme=document.querySelector('.theme'),langBtn=document.querySelector('.language'),nav=document.querySelector('nav'),links=[...document.querySelectorAll('nav a')];
const aboutVisual=document.querySelector('.about-visual');
aboutVisual.innerHTML='<div class="code-window" aria-label="Animated code preview"><div class="code-bar"><span></span><span></span><span></span><b>portfolio.js</b></div><div class="code-screen"><div class="code-line"><i>01</i><code><mark>const</mark> designer = {</code></div><div class="code-line"><i>02</i><code>&nbsp;&nbsp;name: <q>Ahmad</q>,</code></div><div class="code-line"><i>03</i><code>&nbsp;&nbsp;skills: [<q>Branding</q>,</code></div><div class="code-line"><i>04</i><code>&nbsp;&nbsp;&nbsp;&nbsp;<q>Creative Design</q>],</code></div><div class="code-line"><i>05</i><code>&nbsp;&nbsp;passion: <mark>true</mark></code></div><div class="code-line"><i>06</i><code>};</code></div><div class="code-line"><i>07</i><code>designer.<strong>create</strong>();<span class="code-caret"></span></code></div></div></div>';
document.querySelectorAll('.projects article:nth-child(n+4)').forEach(project=>project.remove());
const featuredProject=document.querySelector('.projects article');
featuredProject.classList.add('featured-project');
featuredProject.innerHTML='<div class="project-preview"><img src="assets/shahd-website-preview.png" alt="Screenshot of the Shahd UX/UI portfolio website"><em>01</em><b>WEB<br>DESIGN</b></div><aside><h3>Shahd UX/UI Portfolio Website</h3><p>Website design & development</p><span class="project-cta">View project ↗</span></aside><a class="project-link" href="https://ahmadebrahem9.github.io/shahd-uxui-portfolio/" target="_blank" rel="noopener noreferrer" aria-label="View Shahd UX/UI Portfolio website"></a>';
const projectStyles=document.createElement('style');
projectStyles.textContent='.project-link{position:absolute;z-index:3;inset:0}.featured-project{cursor:pointer}.featured-project .project-preview{position:relative;padding:0;background:#120822}.featured-project .project-preview img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;transition:transform .65s ease}.featured-project .project-preview:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(5,2,12,.08),rgba(5,2,12,.72))}.featured-project .project-preview em,.featured-project .project-preview b{position:relative;z-index:1;margin:24px}.featured-project:hover .project-preview img{transform:scale(1.07)}.featured-project aside{z-index:2;padding-bottom:18px}.project-cta{display:inline-block;margin:9px 3px 0;color:#fff;font-size:.78rem;font-weight:700;letter-spacing:.04em}.featured-project:focus-within{outline:2px solid var(--red2);outline-offset:4px}';
document.head.appendChild(projectStyles);
const codeScreen=document.querySelector('.code-screen');
const codeScenes=[
 [[['keyword','const '],['plain','idea'],['plain',' = '],['string','"creative"'],['plain',';']],[['keyword','const '],['plain','design'],['plain',' = '],['function','create'],['plain','(idea);']],[['plain','design.'],['function','refine'],['plain','();']],[['keyword','return '],['plain','design;']]],
 [[['keyword','function '],['function','buildBrand'],['plain','() {']],[['plain','  '],['keyword','const '],['plain','style = '],['string','"modern"'],['plain',';']],[['plain','  '],['keyword','const '],['plain','details = '],['number','100'],['plain',';']],[['plain','  '],['keyword','return '],['function','launch'],['plain','(style, details);']],[['plain','}']]],
 [[['comment','// Turning ideas into visuals']],[['plain','portfolio.'],['function','add'],['plain','({']],[['plain','  quality: '],['boolean','true'],['plain',',']],[['plain','  passion: '],['string','"always"']],[['plain','});']]]
];
const reduceCodeMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
let codeSceneIndex=0,codeTimer;
const codeWait=ms=>new Promise(resolve=>{codeTimer=setTimeout(resolve,ms)});
async function typeCodeScene(){
 const scene=codeScenes[codeSceneIndex];codeScreen.innerHTML='';
 for(let lineIndex=0;lineIndex<scene.length;lineIndex++){
  const row=document.createElement('div');row.className='typed-code-line';row.innerHTML=`<i>${String(lineIndex+1).padStart(2,'0')}</i><code></code>`;codeScreen.appendChild(row);const output=row.querySelector('code');
  for(const [kind,value] of scene[lineIndex]){const token=document.createElement('span');token.className=`token-${kind}`;output.appendChild(token);for(const char of value){token.textContent+=char;if(!reduceCodeMotion)await codeWait(34+Math.random()*38)}}
  if(!reduceCodeMotion)await codeWait(130);
 }
 const caret=document.createElement('span');caret.className='code-caret';codeScreen.lastElementChild.querySelector('code').appendChild(caret);
 if(reduceCodeMotion)return;
 await codeWait(1900);codeScreen.classList.add('is-changing');await codeWait(280);codeScreen.classList.remove('is-changing');codeSceneIndex=(codeSceneIndex+1)%codeScenes.length;typeCodeScene();
}
typeCodeScene();
const savedTheme=localStorage.getItem('ahmad-theme');if(savedTheme==='light'||(!savedTheme&&matchMedia('(prefers-color-scheme:light)').matches))root.classList.add('light');theme.onclick=()=>{root.classList.toggle('light');localStorage.setItem('ahmad-theme',root.classList.contains('light')?'light':'dark')};
document.querySelector('.menu').onclick=()=>nav.classList.toggle('open');links.forEach(a=>a.onclick=()=>nav.classList.remove('open'));
const tr={
 en:{nav:['Home','About','Services','Portfolio','Contact'],over:["HELLO, IT'S ME",'GET TO KNOW ME','WHAT I CAN DO','SELECTED WORK','GET IN TOUCH'],name:'Ahmad <span>Ibrahim</span>',prefix:"I'm a ",lead:'I turn ideas into clear, memorable visuals — thoughtfully crafted down to the smallest detail.',hero:'My Portfolio <b>→</b>',at:'About <span>Me</span>',role:'Designer & Creative Thinker',ap:["I'm Ahmad. I believe great design is where simplicity meets character. I love building modern visuals that communicate clearly and leave a lasting impression.",'Every project gets my full attention, from the first idea to the final detail.'],ab:"Let's Talk <b>→</b>",st:'My <span>Services</span>',sh:['Creative Design','Visual Identity','Social Content'],sp:['Modern, striking visuals designed to make your message clear and memorable.','A consistent visual language that gives your personal brand a strong presence.','Polished content for social platforms, prepared in professional dimensions.'],more:'Learn more →',wt:'Latest <span>Projects</span>',ph:['Creative Design','Digital Content','Visual Identity','Modern Style','Visual Story','Smart Ideas'],pp:['Identity & Design','Social Media','Branding','Design & Direction','Art Direction','Creative Solutions'],ct:'Contact <span>Me</span>',ci:"Have an idea or a project? I'd love to hear from you.",dl:['WhatsApp','Email','Instagram'],pl:['Your name','Your email','Subject','Your message'],send:'Send Message',foot:'Ahmad. All rights reserved.',words:['Creative Designer','Visual Storyteller','Detail Enthusiast']},
 ar:{nav:['الرئيسية','عني','خدماتي','أعمالي','تواصل معي'],over:['مرحباً، أنا','تعرّف عليّ','ماذا أقدّم','أعمال مختارة','ابقَ على تواصل'],name:'أحمد <span>إبراهيم</span>',prefix:'أنا ',lead:'أحوّل الأفكار إلى تصاميم واضحة ولا تُنسى، مصنوعة بعناية حتى أدق التفاصيل.',hero:'شاهد أعمالي <b>←</b>',at:'من <span>أنا</span>',role:'مصمم وصانع أفكار',ap:['أنا أحمد. أؤمن أن التصميم الرائع يجمع بين البساطة والشخصية. أحب بناء تصاميم عصرية توصل الفكرة بوضوح وتترك انطباعاً مميزاً.','أمنح كل مشروع اهتمامي الكامل، من الفكرة الأولى حتى أدق تفصيل أخير.'],ab:'تواصل معي <b>←</b>',st:'خدماتي <span>الإبداعية</span>',sh:['التصميم الإبداعي','الهوية البصرية','محتوى التواصل'],sp:['تصاميم عصرية وجذابة تجعل رسالتك واضحة ولا تُنسى.','لغة بصرية متناسقة تمنح هويتك حضوراً قوياً.','محتوى أنيق لمنصات التواصل بمقاسات احترافية.'],more:'اعرف المزيد ←',wt:'أحدث <span>أعمالي</span>',ph:['تصميم إبداعي','محتوى رقمي','هوية بصرية','أسلوب حديث','قصة بصرية','أفكار ذكية'],pp:['هوية وتصميم','شبكات التواصل','علامات تجارية','تصميم وإخراج','إخراج فني','حلول إبداعية'],ct:'تواصل <span>معي</span>',ci:'عندك فكرة أو مشروع؟ يسعدني أن أسمع منك.',dl:['واتساب','البريد الإلكتروني','إنستغرام'],pl:['الاسم','البريد الإلكتروني','الموضوع','اكتب رسالتك'],send:'إرسال الرسالة',foot:'أحمد. جميع الحقوق محفوظة.',words:['مصمم ومبدع','صانع أفكار','شغوف بالتفاصيل']}}
tr.en.ph[0]='Shahd UX/UI Portfolio Website';
tr.en.pp[0]='Website design & development';
tr.ar.ph[0]='موقع بورتفوليو شهد UX/UI';
tr.ar.pp[0]='تصميم وتطوير موقع إلكتروني متجاوب';
let lang=localStorage.getItem('ahmad-language')||'en',words=tr[lang].words,w=0,l=0,del=false;const typing=document.querySelector('.typing');
const texts=(s,a)=>document.querySelectorAll(s).forEach((e,i)=>{if(a[i]!=null)e.textContent=a[i]});
function applyLang(code){const t=tr[code];root.lang=code;root.dir=code==='ar'?'rtl':'ltr';langBtn.textContent=code==='ar'?'EN':'AR';texts('nav a',t.nav);texts('.overline',t.over);document.querySelector('.hero h1').innerHTML=t.name;document.querySelector('.hero h2').childNodes[0].textContent=t.prefix;document.querySelector('.lead').textContent=t.lead;document.querySelector('.hero .btn').innerHTML=t.hero;document.querySelector('.about .title').innerHTML=t.at;document.querySelector('.about-copy h3').textContent=t.role;texts('.about-copy>p:not(.overline)',t.ap);document.querySelector('.about-copy .btn').innerHTML=t.ab;document.querySelector('.services .title').innerHTML=t.st;texts('.cards h3',t.sh);texts('.cards p',t.sp);texts('.cards a',[t.more,t.more,t.more]);document.querySelector('.work .title').innerHTML=t.wt;texts('.projects aside h3',t.ph);texts('.projects aside p',t.pp);document.querySelector('.contact .title').innerHTML=t.ct;document.querySelector('.contact .intro').textContent=t.ci;texts('.details small',t.dl);document.querySelectorAll('.contact input,.contact textarea').forEach((e,i)=>e.placeholder=t.pl[i]);document.querySelector('.contact form .btn').textContent=t.send;document.querySelector('footer p').textContent=`© ${new Date().getFullYear()} ${t.foot}`;words=t.words;w=0;l=0;del=false;typing.textContent=words[0];localStorage.setItem('ahmad-language',code)}
langBtn.onclick=()=>{lang=lang==='en'?'ar':'en';applyLang(lang)};applyLang(lang);
function type(){const s=words[w];l+=del?-1:1;typing.textContent=s.slice(0,l);let wait=del?45:85;if(!del&&l===s.length){del=true;wait=1500}else if(del&&l===0){del=false;w=(w+1)%words.length;wait=350}setTimeout(type,wait)}setTimeout(type,700);
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));const sections=[...document.querySelectorAll('main section')];addEventListener('scroll',()=>{let id='home';sections.forEach(s=>{if(scrollY>=s.offsetTop-160)id=s.id});links.forEach(a=>a.classList.toggle('active',a.hash==='#'+id))},{passive:true});const glow=document.querySelector('.cursor-glow');addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'},{passive:true});
