const P='assets/products/';
const products=[
{id:'rare-blush',brand:'Rare Beauty',name:'Soft Pinch Liquid Blush',price:25,cat:'Blush',type:'makeup',img:P+'rare-blush.jpg',best:1,new:0,colors:['#c7837c','#ef8c92','#d88467','#8f5361']},
{id:'rare-highlighter',brand:'Rare Beauty',name:'Positive Light Highlighter',price:28,cat:'Highlighter',type:'makeup',img:P+'rare-highlighter.jpg',best:1,new:0},
{id:'rare-foundation',brand:'Rare Beauty',name:'Liquid Touch Foundation',price:32,cat:'Foundation',type:'makeup',img:P+'rare-foundation.jpg',new:1},
{id:'rare-mascara',brand:'Rare Beauty',name:'Perfect Strokes Mascara',price:24,cat:'Mascara',type:'makeup',img:P+'rare-mascara.jpg'},
{id:'fenty-foundation',brand:'Fenty Beauty',name:"Pro Filt'r Foundation",price:40,cat:'Foundation',type:'makeup',img:P+'fenty-foundation.jpg',best:1},
{id:'fenty-gloss',brand:'Fenty Beauty',name:'Gloss Bomb',price:23,cat:'Lipstick',type:'makeup',img:P+'fenty-gloss.jpg',best:1,new:1},
{id:'fenty-match-stix',brand:'Fenty Beauty',name:'Match Stix',price:33,cat:'Concealer',type:'makeup',img:P+'fenty-match-stix.jpg'},
{id:'fenty-killawatt',brand:'Fenty Beauty',name:'Killawatt Highlighter',price:40,cat:'Highlighter',type:'makeup',img:P+'fenty-killawatt.jpg'},
{id:'dior-lip-glow',brand:'Dior',name:'Dior Addict Lip Glow',price:42,cat:'Lipstick',type:'makeup',img:'https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwf06bcf59/Y0457000/Y0457000_E000001939_E02_RHC.jpg?sw=800',best:1},
{id:'dior-maximizer',brand:'Dior',name:'Dior Lip Maximizer',price:42,cat:'Lipstick',type:'makeup',img:'https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw8e38987f/Y0319000/Y0319000_C031900066_E01_RHC.jpg?sw=800',new:1},
{id:'dior-foundation',brand:'Dior',name:'Dior Forever Foundation',price:60,cat:'Foundation',type:'makeup',img:'https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/en_US/dw5e4619d5/Y0000149/Y0000149_E000001270_E01_RHC.jpg?sw=800'},
{id:'dior-blush',brand:'Dior',name:'Dior Backstage Blush',price:42,cat:'Blush',type:'makeup',img:'https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw89149fbf/Y0000049/Y0000049_E000000576_E01_RHC.jpg?sw=800'},
{id:'ordinary-niacinamide',brand:'The Ordinary',name:'Niacinamide 10% + Zinc 1%',price:6,cat:'Serum',type:'skincare',img:'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwce8a7cdf/Images/products/The%20Ordinary/rdn-niacinamide-10pct-zinc-1pct-30ml.png?sh=800&sm=fit&sw=800',best:1},
{id:'ordinary-hyaluronic',brand:'The Ordinary',name:'Hyaluronic Acid 2% + B5',price:9.9,cat:'Serum',type:'skincare',img:P+'ordinary-hyaluronic.jpg'},
{id:'ordinary-glycolic',brand:'The Ordinary',name:'Glycolic Acid Toner',price:9,cat:'Toner',type:'skincare',img:'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw8b57fa2b/Images/products/The%20Ordinary/ord-glyc-acid-7pct-100ml-Aug-UPC.png?sh=800&sm=fit&sw=800'},
{id:'ordinary-caffeine',brand:'The Ordinary',name:'Caffeine Solution 5% + EGCG',price:9.5,cat:'Eye Care',type:'skincare',img:'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw3c5e95f9/Images/products/The%20Ordinary/2020-08-17-ORD-Product-Caff-Sol-5pct-ECCG-Eye-Serum-updated.png?sh=800&sm=fit&sw=800',new:1},
{id:'cerave-hydrating',brand:'CeraVe',name:'Hydrating Facial Cleanser',price:15.99,cat:'Cleanser',type:'skincare',img:P+'cerave-hydrating.jpg',best:1},
{id:'cerave-foaming',brand:'CeraVe',name:'Foaming Facial Cleanser',price:16.49,cat:'Cleanser',type:'skincare',img:P+'cerave-foaming.jpg'},
{id:'cerave-cream',brand:'CeraVe',name:'Moisturizing Cream',price:18.99,cat:'Moisturizer',type:'skincare',img:P+'cerave-cream.jpg'},
{id:'cosrx-snail-essence',brand:'COSRX',name:'Advanced Snail 96 Essence',price:25,cat:'Serum',type:'skincare',img:P+'cosrx-snail-essence.jpg',best:1},
{id:'cosrx-cleanser',brand:'COSRX',name:'Low pH Good Morning Cleanser',price:14,cat:'Cleanser',type:'skincare',img:P+'cosrx-cleanser.jpg'},
{id:'cosrx-snail-cream',brand:'COSRX',name:'Advanced Snail 92 Cream',price:26,cat:'Moisturizer',type:'skincare',img:P+'cosrx-snail-cream.png',new:1},
{id:'cosrx-bha',brand:'COSRX',name:'BHA Blackhead Power Liquid',price:25,cat:'Acne Care',type:'skincare',img:P+'cosrx-bha.jpg'}
];
let cart=JSON.parse(localStorage.getItem('lina-cart')||'[]'), wishlist=JSON.parse(localStorage.getItem('lina-wish')||'[]');
const app=document.querySelector('#app'),drawer=document.querySelector('#drawer'),overlay=document.querySelector('#overlay'),modal=document.querySelector('#modal');
const save=()=>{localStorage.setItem('lina-cart',JSON.stringify(cart));localStorage.setItem('lina-wish',JSON.stringify(wishlist));updateCounts()};
const updateCounts=()=>{document.querySelector('#cart-count').textContent=cart.reduce((a,x)=>a+x.qty,0);document.querySelector('#wish-count').textContent=wishlist.length};
const money=n=>`$${Number(n).toFixed(2)}`;
const toast=t=>{const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};
function card(p){return `<article class="product-card"><div class="product-media"><button class="wish" data-wish="${p.id}">${wishlist.includes(p.id)?'♥':'♡'}</button><img src="${p.img}" alt="${p.brand} ${p.name}" loading="lazy" onerror="this.closest('.product-media').style.background='linear-gradient(145deg,#ead5d1,#fff)'"><div class="product-name-overlay">${p.name}</div><button class="btn quick" data-quick="${p.id}">Quick View</button></div><div class="product-info"><span class="brand">${p.brand}</span><h3>${p.name}</h3><span class="rating">★★★★★</span><div class="price-row"><span class="price">${money(p.price)}</span><button class="add-mini" data-add="${p.id}">أضيفي للسلة</button></div></div></article>`}
const grid=arr=>`<div class="products-grid">${arr.map(card).join('')}</div>`;
function home(){const cats=[['Face',products[4].img,'makeup'],['Lips',products[5].img,'makeup'],['Eyes',products[3].img,'makeup'],['Skincare',products[16].img,'skincare'],['Sunscreen',products[18].img,'skincare'],['Serums',products[19].img,'skincare']];app.innerHTML=`<section class="hero"><div class="hero-copy"><span class="eyebrow">Curated beauty for every you</span><h1>Glow Starts Here</h1><p>اكتشفي منتجات الجمال والعناية المختارة لكِ من أشهر البراندات العالمية.</p><div><a class="btn" href="#makeup">Shop Makeup</a><a class="btn secondary" href="#skincare">Shop Skincare</a></div></div></section><section class="section"><div class="section-head"><div><span class="eyebrow">Find your ritual</span><h2>Shop by Category</h2></div><p>كل ما تحتاجينه لروتينك اليومي، في مكان واحد وباختيارات تستحق التجربة.</p></div><div class="category-grid">${cats.map(x=>`<a class="category-card" style="background-image:url('${x[1]}')" href="#${x[2]}"><span>${x[0]}</span></a>`).join('')}</div></section><section class="section white"><div class="section-head"><div><span class="eyebrow">Loved by you</span><h2>Best Sellers</h2></div><a class="text-link" href="#makeup">تسوّقي الكل</a></div>${grid(products.filter(x=>x.best).slice(0,8))}</section><section class="section"><div class="section-head"><div><span class="eyebrow">Icons only</span><h2>Shop by Brand</h2></div></div><div class="brands-row">${['Rare Beauty','Fenty Beauty','Dior','The Ordinary','CeraVe','COSRX'].map(x=>`<a href="#brands" class="brand-pill">${x}</a>`).join('')}</div></section><section class="section white"><div class="section-head"><div><span class="eyebrow">Just landed</span><h2>New Arrivals</h2></div></div>${grid(products.filter(x=>x.new))}</section><section class="newsletter"><div><span class="eyebrow">Welcome to LINA</span><h2>Get 10% Off Your First Order</h2></div><form id="newsletter"><input type="email" placeholder="بريدك الإلكتروني" required><button>احصلي على الخصم</button></form></section>`}
function shop(type){const title=type==='makeup'?'Makeup':'Skincare',cats=type==='makeup'?['Foundation','Blush','Lipstick','Mascara','Concealer','Highlighter']:['Cleanser','Moisturizer','Serum','Toner','Sunscreen','Eye Care','Acne Care'];const visual=type==='makeup'?`<section class="section white"><div class="section-head"><div><span class="eyebrow">Choose your look</span><h2>تسوّقي حسب النوع</h2></div></div><div class="makeup-categories">${[['Mascara',products[3]],['Lipstick',products[5]],['Blush',products[0]],['Foundation',products[4]]].map(x=>`<a class="makeup-category" href="#makeup" data-category-jump="${x[0]}"><img src="${x[1].img}" alt="${x[0]}"><strong>${x[0]}</strong></a>`).join('')}</div></section>`:'';app.innerHTML=`<section class="page-hero"><span class="eyebrow">LINA edit</span><h1>${title}</h1><p>${type==='makeup'?'ألوان، لمعة وتغطية تحكي أسلوبك.':'روتين فعّال لبشرة مرتاحة ومتوازنة.'}</p></section>${visual}<section class="shop-layout"><aside class="filters"><div class="filter-group"><h4>Category</h4>${cats.map(x=>`<label><input type="checkbox" value="${x}" data-filter> ${x}</label>`).join('')}</div><div class="filter-group"><h4>Brand</h4>${[...new Set(products.filter(x=>x.type===type).map(x=>x.brand))].map(x=>`<label><input type="checkbox" value="${x}" data-brand> ${x}</label>`).join('')}</div><div class="filter-group"><h4>Price</h4><input id="price-range" type="range" min="10" max="100" value="100"><p>حتى <span id="price-value">$100</span></p></div></aside><div><div class="toolbar"><span id="results-count"></span><select id="sort"><option value="popular">Popular</option><option value="new">Newest</option><option value="low">Price Low to High</option><option value="high">Price High to Low</option></select></div><div id="shop-grid"></div></div></section>`;window.shopType=type;applyFilters()}
function applyFilters(){let a=products.filter(x=>x.type===window.shopType);const c=[...document.querySelectorAll('[data-filter]:checked')].map(x=>x.value),b=[...document.querySelectorAll('[data-brand]:checked')].map(x=>x.value),max=+(document.querySelector('#price-range')?.value||100),sort=document.querySelector('#sort')?.value;if(c.length)a=a.filter(x=>c.includes(x.cat));if(b.length)a=a.filter(x=>b.includes(x.brand));a=a.filter(x=>x.price<=max);if(sort==='low')a.sort((x,y)=>x.price-y.price);if(sort==='high')a.sort((x,y)=>y.price-x.price);if(sort==='new')a.sort((x,y)=>(y.new||0)-(x.new||0));document.querySelector('#shop-grid').innerHTML=grid(a);document.querySelector('#results-count').textContent=`${a.length} منتج`;const v=document.querySelector('#price-value');if(v)v.textContent='$'+max}
function brands(){const bs=['Rare Beauty','Fenty Beauty','Dior','The Ordinary','CeraVe','COSRX'];app.innerHTML=`<section class="page-hero"><span class="eyebrow">The names we trust</span><h1>Brands</h1><p>تشكيلة منتقاة من البراندات التي صنعت فرقًا في عالم الجمال.</p></section><section class="section"><div class="brand-cards">${bs.map(b=>`<a href="#${['The Ordinary','CeraVe','COSRX'].includes(b)?'skincare':'makeup'}" class="brand-card"><span class="eyebrow">Curated by LINA</span><h3>${b}</h3><span>Shop Collection →</span></a>`).join('')}</div></section>`}
function detail(id){const p=products.find(x=>x.id===id)||products[0];app.innerHTML=`<section class="product-detail"><div class="detail-image"><img src="${p.img}" alt="${p.name}"></div><div class="detail-copy"><span class="brand">${p.brand}</span><h1>${p.name}</h1><div class="rating">★★★★★ <small>(128 reviews)</small></div><p class="price">${money(p.price)}</p>${p.colors?`<p>Color: Hope | Joy | Happy | Believe</p><div class="swatches">${p.colors.map(c=>`<button class="swatch" style="background:${c}"></button>`).join('')}</div>`:''}<div><span>Quantity</span><div class="qty"><button data-q="-">−</button><span id="detail-qty">1</span><button data-q="+">+</button></div></div><button class="btn full" data-add="${p.id}" data-detail-add>Add to Cart</button><div class="detail-tabs"><details open><summary>Description</summary><p>تركيبة مختارة بعناية تمنحك نتيجة جميلة ومريحة للاستخدام اليومي.</p></details><details><summary>Ingredients</summary><p>يرجى مراجعة العبوة أو صفحة البراند الرسمية لأحدث قائمة مكونات.</p></details><details><summary>How to Use</summary><p>استخدمي كمية مناسبة وادمجيها تدريجيًا للحصول على النتيجة المرغوبة.</p></details><details><summary>Reviews</summary><p>4.8 من 5 بناءً على تقييمات العملاء.</p></details></div></div></section><section class="section white"><div class="section-head"><h2>You May Also Like</h2></div>${grid(products.filter(x=>x.type===p.type&&x.id!==p.id).slice(0,4))}</section>`}
function offers(){app.innerHTML=`<section class="page-hero"><span class="eyebrow">A little extra</span><h1>Offers</h1><p>خصم 10% على طلبك الأول، وشحن مجاني للطلبات فوق $75.</p></section><section class="section">${grid(products.slice(0,8))}</section>`}
function profile(){app.innerHTML=`<section class="page-hero"><h1>My Account</h1><p>حسابك، طلباتك وقائمة أمنياتك في مكان واحد.</p></section><div class="profile-card"><h2>أهلًا بكِ في LINA</h2><p>لم يتم تسجيل الدخول بعد.</p><button class="btn" data-login>Login / Register</button><h3>Order History</h3><p>لا توجد طلبات سابقة.</p></div>`}
function checkout(){const total=cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);app.innerHTML=`<section class="page-hero"><h1>Checkout</h1></section><div class="checkout-card"><h2>بيانات التوصيل</h2><div class="form-grid"><input placeholder="الاسم الأول"><input placeholder="اسم العائلة"><input class="full" placeholder="العنوان"><input placeholder="المدينة"><input placeholder="رقم الهاتف"><input class="full" placeholder="البريد الإلكتروني"></div><div class="drawer-total"><span>الإجمالي</span><strong>${money(total)}</strong></div><button class="btn full" data-place-order>إتمام الطلب</button></div>`}
function route(){const [r,param]=location.hash.slice(1).split('/');document.querySelectorAll('.main-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===r));if(r==='makeup')shop('makeup');else if(r==='skincare')shop('skincare');else if(r==='brands')brands();else if(r==='offers')offers();else if(r==='product')detail(param);else if(r==='profile')profile();else if(r==='checkout')checkout();else home();window.scrollTo(0,0)}
function add(id,qty=1){const x=cart.find(i=>i.id===id);x?x.qty+=qty:cart.push({id,qty});save();toast('تمت إضافة المنتج إلى السلة')}
function toggleWish(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();route();toast(wishlist.includes(id)?'تمت الإضافة للمفضلة':'تمت الإزالة من المفضلة')}
function showDrawer(mode='cart'){const ids=mode==='wishlist'?wishlist:cart.map(x=>x.id),items=ids.map(id=>products.find(p=>p.id===id)).filter(Boolean);drawer.innerHTML=`<div class="drawer-head"><h2>${mode==='wishlist'?'المفضلة':'Shopping Cart'}</h2><button data-close>✕</button></div>${items.length?items.map(p=>{const q=cart.find(x=>x.id===p.id)?.qty||1;return `<div class="drawer-item"><img src="${p.img}"><div><b>${p.name}</b><small>${p.brand}</small><p>${money(p.price)} × ${q}</p></div><button data-remove="${p.id}" data-mode="${mode}">×</button></div>`}).join(''):`<div class="empty">لا توجد منتجات هنا بعد.</div>`}${mode==='cart'&&items.length?`<div class="drawer-total"><span>الإجمالي</span><strong>${money(cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0))}</strong></div><a class="btn full" href="#checkout" data-close>Checkout</a>`:''}`;drawer.classList.add('open');overlay.classList.add('open')}
function closeUI(){drawer.classList.remove('open');overlay.classList.remove('open');if(modal.open)modal.close()}
function searchModal(){modal.innerHTML=`<div class="modal-content"><div class="drawer-head"><h2>Search</h2><button data-close>✕</button></div><input id="search-box" class="search-input" placeholder="ابحثي باسم المنتج أو البراند..." autofocus><div class="search-results"></div></div>`;modal.showModal();setTimeout(()=>document.querySelector('#search-box').focus(),50)}
function loginModal(){modal.innerHTML=`<div class="modal-content"><div class="drawer-head"><h2>Welcome to LINA</h2><button data-close>✕</button></div><p>سجلي الدخول أو أنشئي حسابًا جديدًا.</p><div class="form-grid"><input class="full" type="email" placeholder="البريد الإلكتروني"><input class="full" type="password" placeholder="كلمة المرور"><button class="btn full" data-auth>Login / Register</button></div></div>`;modal.showModal()}
document.addEventListener('click',e=>{const t=e.target.closest('[data-add],[data-wish],[data-quick],[data-action],[data-close],[data-remove],[data-login],[data-auth],[data-place-order],[data-q],[data-category-jump]');if(!t)return;if(t.dataset.add)add(t.dataset.add,+(document.querySelector('#detail-qty')?.textContent||1));if(t.dataset.wish)toggleWish(t.dataset.wish);if(t.dataset.quick)location.hash='product/'+t.dataset.quick;if(t.dataset.action==='cart')showDrawer();if(t.dataset.action==='wishlist')showDrawer('wishlist');if(t.dataset.action==='search')searchModal();if(t.dataset.action==='account'||t.dataset.login!==undefined)loginModal();if(t.dataset.action==='theme'){const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('lina-theme',next);toast(next==='dark'?'تم تشغيل الوضع الليلي':'تم تشغيل الوضع النهاري')}if(t.dataset.categoryJump){e.preventDefault();const box=[...document.querySelectorAll('[data-filter]')].find(x=>x.value===t.dataset.categoryJump);if(box){document.querySelectorAll('[data-filter]').forEach(x=>x.checked=false);box.checked=true;applyFilters();document.querySelector('.shop-layout').scrollIntoView({behavior:'smooth'})}}if(t.dataset.close!==undefined)closeUI();if(t.dataset.remove){if(t.dataset.mode==='wishlist')wishlist=wishlist.filter(x=>x!==t.dataset.remove);else cart=cart.filter(x=>x.id!==t.dataset.remove);save();showDrawer(t.dataset.mode)}if(t.dataset.auth!==undefined){closeUI();toast('تم تسجيل الدخول بنجاح')}if(t.dataset.placeOrder!==undefined){cart=[];save();toast('تم استلام طلبك بنجاح');setTimeout(()=>location.hash='profile',800)}if(t.dataset.q){const n=document.querySelector('#detail-qty');n.textContent=Math.max(1,+n.textContent+(t.dataset.q==='+'?1:-1))}});
document.addEventListener('input',e=>{if(e.target.matches('[data-filter],[data-brand],#price-range,#sort'))applyFilters();if(e.target.id==='search-box'){const q=e.target.value.toLowerCase(),a=products.filter(p=>(p.name+p.brand).toLowerCase().includes(q)).slice(0,7);document.querySelector('.search-results').innerHTML=a.map(p=>`<a href="#product/${p.id}" data-close class="drawer-item"><img src="${p.img}"><span><b>${p.name}</b><small>${p.brand}</small></span><strong>${money(p.price)}</strong></a>`).join('')}});
document.addEventListener('submit',e=>{if(e.target.id==='newsletter'){e.preventDefault();e.target.reset();toast('كود الخصم LINA10 وصل لبريدك')}});overlay.addEventListener('click',closeUI);window.addEventListener('hashchange',route);document.documentElement.dataset.theme=localStorage.getItem('lina-theme')||'light';updateCounts();route();
